AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order Processor Durable Function for Cloud Testing

Globals:
  Function:
    Runtime: python3.13
    Timeout: 60
    MemorySize: 256

Resources:
  # DynamoDB table for storing completed orders
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'durable-functions-integration-Orders'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Purpose
          Value: DurableFunctionTesting

  OrderProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: order-processor-cloud-test
      Handler: app.lambda_handler
      CodeUri: src/order_processor/
      AutoPublishAlias: dev
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 5
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicDurableExecutionRolePolicy
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable

Outputs:
  OrderProcessorFunctionArn:
    Description: ARN of the Order Processor function
    Value: !GetAtt OrderProcessorFunction.Arn
  
  OrderProcessorFunctionName:
    Description: Name of the Order Processor function
    Value: !Ref OrderProcessorFunction
  
  OrdersTableName:
    Description: Name of the DynamoDB Orders table
    Value: !Ref OrdersTable
    Export:
      Name: !Sub ${AWS::StackName}-OrdersTableName
  
  OrdersTableArn:
    Description: ARN of the DynamoDB Orders table
    Value: !GetAtt OrdersTable.Arn

